export const USER_LOCATION_FASTEST_INTERVAL_HIGH = 1000;
export const USER_LOCATION_UPDATE_INTERVAL_HIGH = 1000;
export const USER_LOCATION_FASTEST_INTERVAL_LOW = 5000;
export const USER_LOCATION_UPDATE_INTERVAL_LOW = 5000;
export const MAP_ANIMATION_DURATION = 300;
export const MAP_DEF_LAT_DELTA = 0.00922;
export const MAP_DEF_LONG_DELTA = 0.00421;
